---
title: "Homework 2"
author: "Christine Lucille Kuryla (clk2162)"
date: "2023-10-03"
output: github_document
---

## Problem 1

```{r setup}
library(tidyverse)
```

Import and clean data from fivethirtyeight datasets of interest.

```{r}

# Import and clean data from fivethirtyeight datasets pols-month

pols_df <- read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = 
           case_match(
             month,
             "01" ~ "january",
             "02" ~ "february",
             "03" ~ "march",
             "04" ~ "april",
             "05" ~ "may",
             "06" ~ "june",
             "07" ~ "july",
             "08" ~ "august",
             "09" ~ "september",
             "10" ~ "october",
             "11" ~ "november",
             "12" ~ "december",
           )) %>%
  mutate(president = case_when(
    prez_dem == 1 ~ "dem",
    prez_dem == 0 ~ "rep"
      )) %>% 
  select(-c("prez_dem", "prez_gop", "day"))


# note that the mutate method for prez_dem == 1 or == 0 was chosen because of the code book, and because there exists values of "2" in prez_gop, which does not agree with the code book. Here we are assuming that prez_rep = 2 and prez_dem = 0 means that the president was republican. 
  

# Import and clean snp.csv 

snp_df <- read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
    separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(month = 
           case_match(
             month,
             "1" ~ "january",
             "2" ~ "february",
             "3" ~ "march",
             "4" ~ "april",
             "5" ~ "may",
             "6" ~ "june",
             "7" ~ "july",
             "8" ~ "august",
             "9" ~ "september",
             "10" ~ "october",
             "11" ~ "november",
             "12" ~ "december",
           )) %>%
  mutate(year = paste0("20",year)) %>%
  relocate(c("year", "month")) %>%
  select(-"day")

# import and tidy unemployment.csv

unemployment_df <- read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    "jan":"dec",
    names_to = "month",
    values_to = "unemployment"
  ) %>% 
    mutate(month = 
           case_match(
             month,
             "jan" ~ "january",
             "feb" ~ "february",
             "mar" ~ "march",
             "apr" ~ "april",
             "may" ~ "may",
             "jun" ~ "june",
             "jul" ~ "july",
             "aug" ~ "august",
             "sep" ~ "september",
             "oct" ~ "october",
             "nov" ~ "november",
             "dec" ~ "december",
           )) %>% 
  mutate(year = as.character(year)) # this is to enable the merge in the next step

```

Join the datasets by mergine snp into pols, and merging unemployment into the result.

```{r}

# Merge snp_df into pols_df

pols_snp_df <- left_join(pols_df, snp_df)

# Merge unemployment data in as well

pols_snp_unemployment_df <- left_join(pols_snp_df, unemployment_df)

```


